
spring:
  datasource:
    name: test  #数据库名
    url: jdbc:mysql://localhost:3306/testDemo #url  testDemo是数据库名称
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.jdbc.Driver  #数据库链接驱动\
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.bean